name: catkin

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v1
    - uses: betwo/github-setup-catkin@v1.1.1
      with:
        ros-version: 'noetic'
        workspace: '$GITHUB_WORKSPACE'
    - run: catkin_make_isolated
    - run: |
        catkin_make_isolated --catkin-make-args run_tests
        chmod +x ./check_test_result.sh
        ./check_test_result.sh
    env:
      QT_QPA_PLATFORM: offscreen
